site_name: 林一寒's wiki
theme:
  name: 'material'
extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-MML-AM_CHTML'
markdown_extensions:
    - admonition
    - pymdownx.arithmatex
    - markdown_include.include:
        base_path: docs
